#!/usr/bin/env bash
# Installs Nginx with the following configurations:

apt-get update
apt-get install -y nginx

sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo /etc/init.d/nginx restart
