#!/usr/bin/env bash
# prints "Best School" 10 times using while loop but if on the 9th prints additional "hi"

a=0

while [ $a -lt 10 ];
do
	echo "Best School"
	if [ $a -eq 8 ]
	then
		echo "Hi"
	fi
	(( a=a+1 ))
done
