#!/usr/bin/env bash
# prints from 1 to 20 except for 4 and 8

a=1

while [ $a -le 20 ];
do
	echo "$a"
	case $a in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( a=a+1 ))
done
